### ISSUE TITLE
Could you also add this too.

### ISSUE THREAD

**Issue by bonelifer** [cabot/defaultavatar#1]
Could you also add this too memberlist profile:
`memberlist.php?mode=viewprofile&u=`

**Comment by cabot** [comment]
Hello,

As no event is available for adding an HTML element, the "no avatar" image must be declared as the container background.
This also means that the potential ranks of users who do not have an avatar will be displayed according to the conditional statements declared in the [memberlist_view.html](https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/styles/prosilver/template/memberlist_view.html#L30-L35) file.

```css
<style>
:root {
	/* Set here the "no avatar" image URL */
	--noAvatarUrl: url({{ T_THEME_PATH }}/images/no_avatar.gif);
	/* Set here the "no avatar" image size (assuming it has an aspect ratio of 1) */
	--noAvatarSize: 80px;
}
#viewprofile:not(:has(.profile-avatar)) .profile-details {
	background: var(--noAvatarUrl) no-repeat 0 0 / var(--noAvatarSize);
	overflow: hidden;
	padding-left: var(--noAvatarSize);
	@media (max-width: 700px) {
		padding: var(--noAvatarSize) 0 0 0;
	}
}
{% if S_VIEWTOPIC or S_VIEW_MESSAGE %}
.no-avatar .avatar-container {
	background: var(--noAvatarUrl) no-repeat 0 0 / cover;
	aspect-ratio: 1;
	height: var(--noAvatarSize);
	margin: 0 0 3px 0;
}
@media (max-width: 700px) {
	.no-avatar .avatar-container {
		float: left;
		height: 32px;
		margin: 0 5px 0 0;
	}
}
{% endif %}
</style>
```
